plugins {
    id 'fabric-loom' version '1.7.4'
    id 'maven-publish'
    id 'mixin'  // добавляем
}

// ... остальное без изменений ...

dependencies {
    minecraft "com.mojang:minecraft:1.21.4"
    mappings "net.fabricmc:yarn:1.21.4+build.1:v2"
    modImplementation "net.fabricmc:fabric-loader:0.15.11"
    // Fabric API не нужна!
    annotationProcessor 'net.fabricmc:sponge-mixin:0.12.5+mixin.0.8.5'
}

mixin {
    add sourceSets.main, "speedmod.refmap.json"
}

// ... остальное
